"""comment

Revision ID: 06459d4a9992
Revises: 195f0b70e16a
Create Date: 2024-04-26 19:02:13.695410

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '06459d4a9992'
down_revision: Union[str, None] = '195f0b70e16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('context_story_window', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'context_story_window')
    # ### end Alembic commands ###
