"""comment

Revision ID: aee1ce50bf6d
Revises: c96c64f5365a
Create Date: 2024-05-29 14:08:53.673065

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aee1ce50bf6d'
down_revision: Union[str, None] = 'c96c64f5365a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queries', 'prompt_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queries', 'prompt_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
