"""independent

Revision ID: 2e38a5a7775b
Revises: b6ceef283228
Create Date: 2024-12-11 20:10:03.659794

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2e38a5a7775b'
down_revision: Union[str, None] = 'b6ceef283228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_prompts_relation', sa.Column('independent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_prompts_relation', 'independent')
    # ### end Alembic commands ###
