"""constr

Revision ID: 6b1871f4bd1a
Revises: c594f54d8e0a
Create Date: 2024-12-11 22:58:16.868797

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6b1871f4bd1a'
down_revision: Union[str, None] = 'c594f54d8e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_prompts_relation', 'is_deleted')
    op.drop_column('scenario_prompts_relation', 'time_update')
    op.drop_column('scenario_prompts_relation', 'time_create')
    op.drop_column('scenario_prompts_relation', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_prompts_relation', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('scenario_prompts_relation', sa.Column('time_create', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('scenario_prompts_relation', sa.Column('time_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('scenario_prompts_relation', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
