"""upd

Revision ID: bfe9ab3009ee
Revises: 6b1871f4bd1a
Create Date: 2025-08-13 16:21:56.775530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe9ab3009ee'
down_revision: Union[str, None] = '6b1871f4bd1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts', 'is_open',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts', 'is_open',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
