"""comment

Revision ID: 34a04d880b69
Revises: adaf4fdf918e
Create Date: 2024-04-26 14:26:34.929283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a04d880b69'
down_revision: Union[str, None] = 'adaf4fdf918e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('queries', sa.Column('prompt_id', sa.UUID(), nullable=True))
    op.drop_constraint('queries_prompt_fkey', 'queries', type_='foreignkey')
    op.drop_constraint('queries_user_fkey', 'queries', type_='foreignkey')
    op.create_foreign_key(None, 'queries', 'prompts', ['prompt_id'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'queries', 'users', ['user_id'], ['uuid'], ondelete='CASCADE')
    op.drop_column('queries', 'prompt')
    op.drop_column('queries', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('user', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('queries', sa.Column('prompt', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.create_foreign_key('queries_user_fkey', 'queries', 'users', ['user'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key('queries_prompt_fkey', 'queries', 'prompts', ['prompt'], ['uuid'], ondelete='CASCADE')
    op.drop_column('queries', 'prompt_id')
    op.drop_column('queries', 'user_id')
    # ### end Alembic commands ###
