"""comment

Revision ID: 4ae4e6b8ea58
Revises: b36d717baefc
Create Date: 2024-04-26 14:15:37.193829

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ae4e6b8ea58'
down_revision: Union[str, None] = 'b36d717baefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('query', sa.String(), nullable=False))
    op.drop_constraint('queries_user_id_fkey', 'queries', type_='foreignkey')
    op.drop_constraint('queries_prompt_id_fkey', 'queries', type_='foreignkey')
    op.drop_column('queries', 'prompt_id')
    op.drop_column('queries', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('queries', sa.Column('prompt_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('queries_prompt_id_fkey', 'queries', 'prompts', ['prompt_id'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key('queries_user_id_fkey', 'queries', 'users', ['user_id'], ['uuid'], ondelete='CASCADE')
    op.drop_column('queries', 'query')
    # ### end Alembic commands ###
