"""comment

Revision ID: 5a57e3785626
Revises: c0b9cd14a332
Create Date: 2024-04-22 18:38:07.176568

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a57e3785626'
down_revision: Union[str, None] = 'c0b9cd14a332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'balance',
               existing_type=sa.NUMERIC(precision=10, scale=10),
               type_=sa.Numeric(precision=11, scale=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'balance',
               existing_type=sa.Numeric(precision=11, scale=5),
               type_=sa.NUMERIC(precision=10, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###
