"""create account relation

Revision ID: 73d37601da12
Revises: ee674b93ac09
Create Date: 2024-04-16 19:23:43.340937

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '73d37601da12'
down_revision: Union[str, None] = 'ee674b93ac09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('prompts', 'account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('prompts', 'price_usage',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts', 'price_usage',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('prompts', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('prompts', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
