"""comment

Revision ID: a30ebaffd887
Revises: 8056c22c9fc1
Create Date: 2024-04-30 14:20:51.400374

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a30ebaffd887'
down_revision: Union[str, None] = '8056c22c9fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('time_create', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
