"""comment

Revision ID: b36d717baefc
Revises: 6a650c4b7577
Create Date: 2024-04-26 13:47:43.898088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36d717baefc'
down_revision: Union[str, None] = '6a650c4b7577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('prompt_id', sa.UUID(), nullable=True))
    op.drop_constraint('queries_user_id_key', 'queries', type_='unique')
    op.create_foreign_key(None, 'queries', 'prompts', ['prompt_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.create_unique_constraint('queries_user_id_key', 'queries', ['user_id'])
    op.drop_column('queries', 'prompt_id')
    # ### end Alembic commands ###
