"""user models

Revision ID: d8416beb6158
Revises: cb93492dac36
Create Date: 2024-04-16 14:02:49.085823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8416beb6158"
down_revision: Union[str, None] = "cb93492dac36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompts",
        sa.Column("price_usage", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.alter_column("prompts", "account_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("prompts", "account_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("prompts", "price_usage")
    # ### end Alembic commands ###
